import type { AppLocale } from '@/features/settings/settings-storage';

export type GoalDetailCopy = {
  back: string; loading: string; loadErrorTitle: string; loadErrorDetail: string; retryLoad: string;
  goalSuffix: string; titleLabel: string; sessionTarget: string; focusTarget: string; targetSessions: string; targetMinutes: string;
  save: string; cancel: string; reload: string; completed: string; completedDetail: string; statusDetail: string;
  progress: string; target: string; completion: string; progressDetail: string; edit: string; deleteConfirmTitle: string;
  deleteDetail: string; deleteAndKeepTasks: string; keepGoal: string; delete: string; startFocus: string; unavailable: string;
  unavailableDetail: string; invalidSessions: string; invalidMinutes: string; conflictSave: string; saveError: string; conflictDelete: string; deleteError: string;
};

const COPY: Record<AppLocale, GoalDetailCopy> = {
  en: { back: 'Back to Goals', loading: 'Loading goal', loadErrorTitle: 'This goal could not be loaded.', loadErrorDetail: 'Your saved goals have not been changed. Try again to reload this goal.', retryLoad: 'Retry loading goal', goalSuffix: 'GOAL', titleLabel: 'Goal title', sessionTarget: 'Session target', focusTarget: 'Focus target in minutes', targetSessions: 'Target sessions', targetMinutes: 'Target focus minutes', save: 'Save goal changes', cancel: 'Cancel editing', reload: 'Reload goal', completed: 'Goal complete', completedDetail: 'You reached this goal. Your recorded focus and session history remain part of your progress.', statusDetail: 'This goal is', progress: 'PROGRESS', target: 'TARGET', completion: 'COMPLETION', progressDetail: 'Progress updates from completed focus sessions saved on this device.', edit: 'Edit goal', deleteConfirmTitle: 'Delete this goal?', deleteDetail: 'Linked tasks will remain and become unlinked. Focus sessions and history will remain unchanged.', deleteAndKeepTasks: 'Delete goal and keep tasks', keepGoal: 'Keep goal', delete: 'Delete goal', startFocus: 'Start a focus session', unavailable: 'Goal unavailable', unavailableDetail: 'This goal could not be found on this device.', invalidSessions: 'Enter a whole number of sessions.', invalidMinutes: 'Enter a valid focus-time target in minutes.', conflictSave: 'This goal changed elsewhere. Reload it before editing so newer progress settings are not overwritten.', saveError: 'This goal could not be saved. Your saved goal is unchanged; try again.', conflictDelete: 'This goal changed elsewhere. Reload it before deleting so newer data is not removed.', deleteError: 'This goal could not be deleted. The goal, linked tasks and focus history are unchanged; try again.' },
  si: { back: 'ඉලක්ක වෙත ආපසු', loading: 'ඉලක්කය පූරණය කරමින්', loadErrorTitle: 'මෙම ඉලක්කය පූරණය කළ නොහැක.', loadErrorDetail: 'ඔබේ සුරකින ලද ඉලක්ක වෙනස් කර නැත. මෙම ඉලක්කය නැවත පූරණය කිරීමට උත්සාහ කරන්න.', retryLoad: 'ඉලක්කය නැවත පූරණය කරන්න', goalSuffix: 'ඉලක්කය', titleLabel: 'ඉලක්කයේ නම', sessionTarget: 'සැසි ඉලක්කය', focusTarget: 'අවධානම් මිනිත්තු ඉලක්කය', targetSessions: 'ඉලක්ක සැසි', targetMinutes: 'ඉලක්ක අවධානම් මිනිත්තු', save: 'ඉලක්ක වෙනස්කම් සුරකින්න', cancel: 'සංස්කරණය නවත්වන්න', reload: 'ඉලක්කය නැවත පූරණය කරන්න', completed: 'ඉලක්කය සම්පූර්ණයි', completedDetail: 'ඔබ මෙම ඉලක්කය ළඟා කරගෙන ඇත. ඔබේ සටහන් කළ අවධානය සහ සැසි ඉතිහාසය ඔබේ ප්‍රගතියේ කොටසක් ලෙස පවතී.', statusDetail: 'මෙම ඉලක්කයේ තත්ත්වය', progress: 'ප්‍රගතිය', target: 'ඉලක්කය', completion: 'සම්පූර්ණත්වය', progressDetail: 'මෙම උපාංගයේ සුරකින ලද සම්පූර්ණ කළ අවධානම් සැසි අනුව ප්‍රගතිය යාවත්කාලීන වේ.', edit: 'ඉලක්කය සංස්කරණය කරන්න', deleteConfirmTitle: 'මෙම ඉලක්කය මකන්නද?', deleteDetail: 'සම්බන්ධිත කාර්යයන් පවතින නමුත් සම්බන්ධතාව ඉවත් වේ. අවධානම් සැසි සහ ඉතිහාසය වෙනස් නොවේ.', deleteAndKeepTasks: 'ඉලක්කය මකා කාර්යයන් තබාගන්න', keepGoal: 'ඉලක්කය තබාගන්න', delete: 'ඉලක්කය මකන්න', startFocus: 'අවධානම් සැසියක් ආරම්භ කරන්න', unavailable: 'ඉලක්කය ලබාගත නොහැක', unavailableDetail: 'මෙම උපාංගයේ මෙම ඉලක්කය හමු නොවීය.', invalidSessions: 'සම්පූර්ණ සංඛ්‍යාවක් ලෙස සැසි ගණන ඇතුළත් කරන්න.', invalidMinutes: 'වලංගු අවධානම් මිනිත්තු ඉලක්කයක් ඇතුළත් කරන්න.', conflictSave: 'මෙම ඉලක්කය වෙනත් තැනක වෙනස් වී ඇත. නව ප්‍රගති සැකසුම් මත ලියවීම වැළැක්වීමට පෙර නැවත පූරණය කරන්න.', saveError: 'මෙම ඉලක්කය සුරැකිය නොහැක. සුරකින ලද ඉලක්කය වෙනස් කර නැත; නැවත උත්සාහ කරන්න.', conflictDelete: 'මෙම ඉලක්කය වෙනත් තැනක වෙනස් වී ඇත. නව දත්ත මැකීම වැළැක්වීමට පෙර නැවත පූරණය කරන්න.', deleteError: 'මෙම ඉලක්කය මැකිය නොහැක. ඉලක්කය, සම්බන්ධිත කාර්යයන් සහ අවධානම් ඉතිහාසය වෙනස් කර නැත; නැවත උත්සාහ කරන්න.' },
  ta: { back: 'இலக்குகளுக்குத் திரும்பு', loading: 'இலக்கு ஏற்றப்படுகிறது', loadErrorTitle: 'இந்த இலக்கை ஏற்ற முடியவில்லை.', loadErrorDetail: 'சேமித்த இலக்குகள் மாற்றப்படவில்லை. இந்த இலக்கை மீண்டும் ஏற்ற முயற்சிக்கவும்.', retryLoad: 'இலக்கை மீண்டும் ஏற்றவும்', goalSuffix: 'இலக்கு', titleLabel: 'இலக்கு பெயர்', sessionTarget: 'அமர்வு இலக்கு', focusTarget: 'கவன நிமிட இலக்கு', targetSessions: 'இலக்கு அமர்வுகள்', targetMinutes: 'இலக்கு கவன நிமிடங்கள்', save: 'இலக்கு மாற்றங்களைச் சேமிக்கவும்', cancel: 'திருத்தத்தை ரத்து செய்யவும்', reload: 'இலக்கை மீண்டும் ஏற்றவும்', completed: 'இலக்கு முடிந்தது', completedDetail: 'இந்த இலக்கை அடைந்துள்ளீர்கள். பதிவு செய்த கவனமும் அமர்வு வரலாறும் உங்கள் முன்னேற்றத்தின் பகுதியாக இருக்கும்.', statusDetail: 'இந்த இலக்கின் நிலை', progress: 'முன்னேற்றம்', target: 'இலக்கு', completion: 'நிறைவு', progressDetail: 'இந்தச் சாதனத்தில் சேமித்த முடிக்கப்பட்ட கவன அமர்வுகளிலிருந்து முன்னேற்றம் புதுப்பிக்கப்படும்.', edit: 'இலக்கைத் திருத்தவும்', deleteConfirmTitle: 'இந்த இலக்கை நீக்கவா?', deleteDetail: 'இணைக்கப்பட்ட பணிகள் இருக்கும்; இணைப்பு நீக்கப்படும். கவன அமர்வுகளும் வரலாறும் மாறாது.', deleteAndKeepTasks: 'இலக்கை நீக்கி பணிகளை வைத்திருக்கவும்', keepGoal: 'இலக்கை வைத்திருக்கவும்', delete: 'இலக்கை நீக்கவும்', startFocus: 'கவன அமர்வைத் தொடங்கவும்', unavailable: 'இலக்கு கிடைக்கவில்லை', unavailableDetail: 'இந்தச் சாதனத்தில் இந்த இலக்கைக் காணவில்லை.', invalidSessions: 'முழு அமர்வுகளின் எண்ணிக்கையை உள்ளிடவும்.', invalidMinutes: 'சரியான கவன நேர இலக்கை நிமிடங்களில் உள்ளிடவும்.', conflictSave: 'இந்த இலக்கு வேறு இடத்தில் மாற்றப்பட்டுள்ளது. புதிய முன்னேற்ற அமைப்புகளை மேலெழுதாமல் இருக்க மீண்டும் ஏற்றவும்.', saveError: 'இந்த இலக்கைச் சேமிக்க முடியவில்லை. சேமித்த இலக்கு மாற்றப்படவில்லை; மீண்டும் முயற்சிக்கவும்.', conflictDelete: 'இந்த இலக்கு வேறு இடத்தில் மாற்றப்பட்டுள்ளது. புதிய தரவை நீக்காமல் இருக்க மீண்டும் ஏற்றவும்.', deleteError: 'இந்த இலக்கை நீக்க முடியவில்லை. இலக்கு, இணைக்கப்பட்ட பணிகள் மற்றும் கவன வரலாறு மாற்றப்படவில்லை; மீண்டும் முயற்சிக்கவும்.' },
};

export function getGoalDetailCopy(locale: AppLocale): GoalDetailCopy { return COPY[locale] ?? COPY.en; }
