import type { AppLocale } from '@/features/settings/settings-storage';

export type ProgressPageCopy = {
  eyebrow: string; title: string; subtitle: string; loading: string; loadErrorLabel: string; loadErrorTitle: string;
  loadErrorDetail: string; retry: string; unavailableLabel: string; unavailableTitle: string; unavailableDetail: string;
  emptyLabel: string; emptyTitle: string; emptyDetail: string; viewHistory: string; calendar: string; week: string;
  month: string; allTime: string; focusTime: string; sessions: string; tasksDone: string; insightEyebrow: string;
  oneBlock: string; blocks: string; insightDetail: string; weekFocus: string; goals: string; sessionsWord: string;
  viewRewards: string;
};

const COPY: Record<AppLocale, ProgressPageCopy> = {
  en: { eyebrow: 'PROGRESS', title: 'Notice your rhythm.', subtitle: 'A clear view of the focus time you have protected.', loading: 'Loading progress', loadErrorLabel: 'Progress could not be loaded', loadErrorTitle: 'Your progress is still here.', loadErrorDetail: 'We couldn’t read your saved sessions just now. Your data hasn’t been changed.', retry: 'Try again', unavailableLabel: 'Progress summary unavailable', unavailableTitle: 'Your saved progress needs a refresh.', unavailableDetail: 'We found records that could not be safely combined. Your saved data hasn’t been changed.', emptyLabel: 'No progress available yet', emptyTitle: 'Your pattern will appear here.', emptyDetail: 'Complete a focus session to start building a quiet, useful record of your work.', viewHistory: 'View session history', calendar: 'Calendar periods use {zone} time. Weeks begin Monday.', week: 'This week', month: 'This month', allTime: 'All time', focusTime: 'FOCUS TIME', sessions: 'SESSIONS', tasksDone: 'TASKS DONE', insightEyebrow: 'YOUR PROGRESS', oneBlock: 'One block protected.', blocks: 'blocks protected.', insightDetail: 'Focus time includes time actually focused, even in sessions ended early. Session count includes completed sessions only.', weekFocus: 'This week’s focus', goals: 'Your goals', sessionsWord: 'sessions', viewRewards: 'View rewards' },
  si: { eyebrow: 'ප්‍රගතිය', title: 'ඔබේ රිද්මය හඳුනාගන්න.', subtitle: 'ඔබ ආරක්ෂා කළ අවධානම් කාලය පැහැදිලිව බලන්න.', loading: 'ප්‍රගතිය පූරණය කරමින්', loadErrorLabel: 'ප්‍රගතිය පූරණය කළ නොහැක', loadErrorTitle: 'ඔබේ ප්‍රගතිය මෙහිම ඇත.', loadErrorDetail: 'ඔබේ සුරකින ලද සැසි දැන් කියවිය නොහැකි විය. ඔබේ දත්ත වෙනස් කර නැත.', retry: 'නැවත උත්සාහ කරන්න', unavailableLabel: 'ප්‍රගති සාරාංශය ලබාගත නොහැක', unavailableTitle: 'ඔබේ සුරකින ලද ප්‍රගතිය නැවුම් කළ යුතුයි.', unavailableDetail: 'ආරක්ෂිතව එකතු කළ නොහැකි වාර්තා හමු විය. ඔබේ දත්ත වෙනස් කර නැත.', emptyLabel: 'තවම ප්‍රගතියක් නැත', emptyTitle: 'ඔබේ රටාව මෙහි පෙන්වනු ඇත.', emptyDetail: 'ඔබේ වැඩ පිළිබඳ සන්සුන්, ප්‍රයෝජනවත් සටහනක් සෑදීමට අවධානම් සැසියක් සම්පූර්ණ කරන්න.', viewHistory: 'සැසි ඉතිහාසය බලන්න', calendar: '{zone} වේලාව භාවිත වේ. සති සඳුදා ආරම්භ වේ.', week: 'මෙම සතිය', month: 'මෙම මාසය', allTime: 'සියලු කාලය', focusTime: 'අවධානම් කාලය', sessions: 'සැසි', tasksDone: 'නිම කළ කාර්ය', insightEyebrow: 'ඔබේ ප්‍රගතිය', oneBlock: 'එක් කොටසක් ආරක්ෂා කළා.', blocks: 'කොටස් ආරක්ෂා කළා.', insightDetail: 'ඉක්මනින් අවසන් වූ සැසිවල ඇත්තටම අවධානය යොමු කළ කාලයත් ඇතුළත් වේ. සැසි ගණනට සම්පූර්ණ කළ සැසි පමණක් ඇතුළත් වේ.', weekFocus: 'මෙම සතියේ අවධානය', goals: 'ඔබේ ඉලක්ක', sessionsWord: 'සැසි', viewRewards: 'තෑගි බලන්න' },
  ta: { eyebrow: 'முன்னேற்றம்', title: 'உங்கள் ஓட்டத்தை கவனியுங்கள்.', subtitle: 'நீங்கள் பாதுகாத்த கவன நேரத்தின் தெளிவான பார்வை.', loading: 'முன்னேற்றம் ஏற்றப்படுகிறது', loadErrorLabel: 'முன்னேற்றத்தை ஏற்ற முடியவில்லை', loadErrorTitle: 'உங்கள் முன்னேற்றம் இங்கேயே உள்ளது.', loadErrorDetail: 'சேமித்த அமர்வுகளை இப்போது படிக்க முடியவில்லை. உங்கள் தரவு மாற்றப்படவில்லை.', retry: 'மீண்டும் முயற்சிக்கவும்', unavailableLabel: 'முன்னேற்றச் சுருக்கம் கிடைக்கவில்லை', unavailableTitle: 'சேமித்த முன்னேற்றத்தைப் புதுப்பிக்க வேண்டும்.', unavailableDetail: 'பாதுகாப்பாக இணைக்க முடியாத பதிவுகள் கிடைத்தன. உங்கள் தரவு மாற்றப்படவில்லை.', emptyLabel: 'முன்னேற்றம் இன்னும் இல்லை', emptyTitle: 'உங்கள் நடை இங்கே தோன்றும்.', emptyDetail: 'உங்கள் பணியின் அமைதியான பயனுள்ள பதிவை உருவாக்க ஒரு கவன அமர்வை முடிக்கவும்.', viewHistory: 'அமர்வு வரலாற்றைப் பார்க்கவும்', calendar: '{zone} நேரம் பயன்படுத்தப்படுகிறது. வாரங்கள் திங்கட்கிழமை தொடங்கும்.', week: 'இந்த வாரம்', month: 'இந்த மாதம்', allTime: 'எல்லா நேரமும்', focusTime: 'கவன நேரம்', sessions: 'அமர்வுகள்', tasksDone: 'முடிக்கப்பட்ட பணிகள்', insightEyebrow: 'உங்கள் முன்னேற்றம்', oneBlock: 'ஒரு தொகுதி பாதுகாக்கப்பட்டது.', blocks: 'தொகுதிகள் பாதுகாக்கப்பட்டன.', insightDetail: 'முன்கூட்டியே முடிக்கப்பட்ட அமர்வுகளின் உண்மையான கவன நேரமும் சேர்க்கப்படும். அமர்வு எண்ணிக்கையில் முடிக்கப்பட்ட அமர்வுகள் மட்டுமே சேரும்.', weekFocus: 'இந்த வார கவனம்', goals: 'உங்கள் இலக்குகள்', sessionsWord: 'அமர்வுகள்', viewRewards: 'வெகுமதிகளைப் பார்க்கவும்' },
};

export function getProgressCopy(locale: AppLocale): ProgressPageCopy {
  return COPY[locale] ?? COPY.en;
}
